name = "cloudflare-tempemail"
main = "src/worker.ts"
compatibility_date = "2025-04-01"
compatibility_flags = ["nodejs_compat"]
keep_vars = true

[vars]
PREFIX = "tmp"

DEFAULT_DOMAINS = ["echoways.org"]
DOMAINS = ["echoways.org"]

JWT_SECRET = "echoways-temp-mail-2026-05-16-random-secret-change-later"

ENABLE_USER_CREATE_EMAIL = true
ENABLE_USER_DELETE_EMAIL = true
ENABLE_AUTO_REPLY = false

BLACK_LIST = ""

[[d1_databases]]
binding = "DB"
database_name = "cloudtempmail"
database_id = "174ed722-1e20-4633-adf5-197410483ef0"
