name = "cloudflare-tempemail"
main = "src/worker.ts"
compatibility_date = "2025-04-01"
compatibility_flags = ["nodejs_compat"]
keep_vars = true

[assets]
directory = "../frontend/dist/"
binding = "ASSETS"
run_worker_first = true

[vars]
PREFIX = "tmp"

DEFAULT_DOMAINS = ["echoways.org", "edu.echoways.org"]
DOMAINS = ["echoways.org", "edu.echoways.org"]

JWT_SECRET = "echoways-7f6b9c2a-5d81-4b98-9d25-random-20260516"

ADMIN_PASSWORDS = ["QAZwsx963"]

ENABLE_USER_CREATE_EMAIL = true
ENABLE_USER_DELETE_EMAIL = true
ENABLE_AUTO_REPLY = false

BLACK_LIST = ""

[[d1_databases]]
binding = "DB"
database_name = "cloudtempmail"
database_id = "174ed722-1e20-4633-adf5-197410483ef0"
